In [267]:
import pandas as pd
import numpy as np

In [268]:
data=pd.read_csv('drug200.csv')
data.head()

Age Sex      BP Cholesterol  Na_to_K   Drug
0   23   F    HIGH        HIGH   25.355  DrugY
1   47   M     LOW        HIGH   13.093  drugC
2   47   M     LOW        HIGH   10.114  drugC
3   28   F  NORMAL        HIGH    7.798  drugX
4   61   F     LOW        HIGH   18.043  DrugY

In [269]:
data.shape

(200, 6)

In [270]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 6 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   Age          200 non-null    int64  
 1   Sex          200 non-null    object 
 2   BP           200 non-null    object 
 3   Cholesterol  200 non-null    object 
 4   Na_to_K      200 non-null    float64
 5   Drug         200 non-null    object 
dtypes: float64(1), int64(1), object(4)
memory usage: 9.5+ KB


In [271]:
data.describe()

Age     Na_to_K
count  200.000000  200.000000
mean    44.315000   16.084485
std     16.544315    7.223956
min     15.000000    6.269000
25%     31.000000   10.445500
50%     45.000000   13.936500
75%     58.000000   19.380000
max     74.000000   38.247000

In [272]:
data.duplicated().sum()

0

In [273]:
data.head()

Age Sex      BP Cholesterol  Na_to_K   Drug
0   23   F    HIGH        HIGH   25.355  DrugY
1   47   M     LOW        HIGH   13.093  drugC
2   47   M     LOW        HIGH   10.114  drugC
3   28   F  NORMAL        HIGH    7.798  drugX
4   61   F     LOW        HIGH   18.043  DrugY

In [274]:
data['Sex'].unique()

array(['F', 'M'], dtype=object)

In [275]:
def SextoN(x):
   if x=='M':
      return 0
   else:
      return 1
data['Sex']=data['Sex'].apply(SextoN)


In [276]:
data['Sex'].unique()

array([1, 0], dtype=int64)

In [277]:
data['BP'].unique()

array(['HIGH', 'LOW', 'NORMAL'], dtype=object)

In [278]:
def BPtoN(x):
    if x=='LOW':
       return 0
    elif x=='NORMAL':
       return 1
    else:
       return 2
data['BP']=data['BP'].apply(BPtoN)

In [279]:
data['BP'].unique()

array([2, 0, 1], dtype=int64)

In [280]:
data['Cholesterol'].unique()

array(['HIGH', 'NORMAL'], dtype=object)

In [281]:
def CholesteroltoN(x):
    if x=='NORMAL':
       return 0
    else:
       return 1
data['Cholesterol']=data['Cholesterol'].apply(CholesteroltoN)

In [282]:
data['Cholesterol'].unique()

array([1, 0], dtype=int64)

In [283]:
data.head()

Age  Sex  BP  Cholesterol  Na_to_K   Drug
0   23    1   2            1   25.355  DrugY
1   47    0   0            1   13.093  drugC
2   47    0   0            1   10.114  drugC
3   28    1   1            1    7.798  drugX
4   61    1   0            1   18.043  DrugY

In [284]:
X=data.iloc[:,:-1].values
Y=data.iloc[:,1].values

In [285]:
X.shape

(200, 5)

In [286]:
Y.shape

(200,)

In [287]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(X, Y, test_size = 0.2, random_state = 0)

In [288]:
from sklearn.tree import DecisionTreeClassifier as dtc
from sklearn.metrics import accuracy_score
model = dtc(criterion = 'entropy', max_depth = 4)
model.fit(x_train, y_train)

y_pred = model.predict(x_test)
acc = accuracy_score(y_test,y_pred)


In [289]:
acc

1.0